# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfd58d33dc825d940f7f83698de4ca0227ffa943080b2a31ff8a5c0c2dc6f75fb73c9c0c4db2465a84d7c635ed02b371dfa22eac244ffb070edfed6d14678f5e

test:
  secret_key_base: d0826bd9cd2d16c1321b4a8da0d081db174585c84b5082903668cd9b3f344bbc96231260b560ec006dea19a39f45ac94b87bdea794e296e40026e34acaae2540

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
